<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CORP1B4" failures="0" tests="8" name="UberAppTim24.tests.PassengerStartRideTest" time="76.798" errors="1" timestamp="1 Mar 2023 16:23:19 GMT">
  <testcase classname="UberAppTim24.tests.PassengerStartRideTest" name="addFavouriteRideTest" time="6.547"/>
  <testcase classname="UberAppTim24.tests.PassengerStartRideTest" name="createScheduledRideTest" time="12.723"/>
  <testcase classname="UberAppTim24.tests.PassengerStartRideTest" name="linkUsersTest" time="13.699"/>
  <testcase classname="UberAppTim24.tests.PassengerStartRideTest" name="markBabiesAndPetsInRideTest" time="6.658"/>
  <testcase classname="UberAppTim24.tests.PassengerStartRideTest" name="selectVehicleTypeRideTest" time="5.833"/>
  <testcase classname="UberAppTim24.tests.PassengerStartRideTest" name="simpleCreateRideTest" time="13.029"/>
  <testcase classname="UberAppTim24.tests.PassengerStartRideTest" name="alreadyInRideTest" time="5.085">
    <error message="expected:&lt;uspešno kreirana vožnja!&gt; but was:&lt;Putnik stefanium@mail.com je vec u aktivnoj voznji&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<uspešno kreirana vožnja!> but was:<Putnik stefanium@mail.com je vec u aktivnoj voznji>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at UberAppTim24.tests.PassengerStartRideTest.alreadyInRideTest(PassengerStartRideTest.java:367)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- alreadyInRideTest -->
  <testcase classname="UberAppTim24.tests.PassengerStartRideTest" name="selectLocationsByClickingOnMapTest" time="13.224"/>
</testsuite> <!-- UberAppTim24.tests.PassengerStartRideTest -->
